### ISSUE TITLE
Proposal: Adding the ms-dotnettools.csdevkit extension dependence

### ISSUE THREAD

**Issue by joined72** [williamoberg/godot-dotnet-tools#3]
Adding the ms-dotnettools.csdevkit dependence, will automatically install the entire MS C# ecosystem, not requiring the user to install it manually!

**Comment by williamoberg** [comment]
I get that this might be useful for some, but since the extension itself doesn't need it to function, adding an unnecessary dependency does not feel right. I'd rather have users choose to install the Dev Kit for themselves.

Also, because the MS Devkit is proprietary and has some pretty strict licencing terms, I feel like it doesn't fit the Godot ecosystem.

I myself, for example, don't use the DevKit at all. The standard C# extension with omnisharp has all you need for this extension.

**Comment by joined72** [comment]
OK, I didn't know, thanks.
